// react-app/modules/pages/components/Writing.js
import React from 'react';
import List from '../../core/components/List';
import { EditingLinks, WritingLinks } from '../data';
import Page from './Page';

const Writing = () => (
  <Page title="writing">
    <List items={WritingLinks} />
    <h1>editing</h1>
    <List items={EditingLinks} />
  </Page>
);

export default Writing;

// vue-app/pages/writing.vue
<script>
  import list from '../components/list';
  import { WritingLinks } from '../../react-app/modules/pages/data';

  export default {
    components: {
      list
    },
    props: {
      items: {
        type: Array,
        default: WritingLinks
      }
    }
  }
</script>

<template>
  <page title="writing">
    <list :items="items"></list>
  </page>
</template >
