// vue-app/components/list.vue
<script>
  export default {
    props: {
      items: {
        type: Array
      }
    }
  }
</script>

<template>
  <div class=${wrapper}>
    <div class=${item} v-for="i in items">
      <a :href="i.url">{{i.label}}</a>
      <div v-if="i.postLabel" >{{i.postLabel}}</div>
    </div>
  </div>
</template>

<style>

  .wrapper {
    display: flex;
    flex-direction: column;
  }

  .item {
    margin-bottom: 15px;
  }

  .item > div {
    font-size: 0.8em;
  }

</style>

// react-app/modules/core/components/List.js
import React from 'react';
import PropTypes from 'prop-types';
import styles from '../css/List.css';

const List = ({ items }) => (
  <div className={styles.wrapper}>
    {items.map(i => (
      <div className={styles.item} key={i.label}>
        <a href={i.url}>{i.label}</a>
        <div>{i.postLabel && `${i.postLabel}`}</div>
      </div>
    ))}
  </div>
);

export default List;

List.propTypes = {
  items: PropTypes.arrayOf(PropTypes.object)
};
